---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-cloud-cluster-monitor
  region: us-east-1
  version: '1.28'
availabilityZones:
  - us-east-1a
  - us-east-1b
  - us-east-1c
  - us-east-1d
managedNodeGroups:
  - name: general
    instanceType: t2.micro
    desiredCapacity: 1
  - name: spot
    privateNetworking: true
    instanceType: t2.micro
    desiredCapacity: 1
